# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:23:34+00:00



import argparse
import json
import os
from typing import *
from typing import Optional
from uuid import UUID

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, UnsuportedSecurityStub
from fastapi import Header, Query

from models import (
    Asset,
    Assets,
    AssetStatusQueryParam,
    AssetType,
    AssetTypesGetResponse,
    OrderBy,
    Setting,
    SortDirection,
)

app = MCPProxy(
    contact={
        'email': 'api@xero.com',
        'name': 'Xero Platform Team',
        'url': 'https://developer.xero.com',
        'x-twitter': 'XeroAPI',
    },
    description='The Assets API exposes fixed asset related functions of the Xero Accounting application and can be used for a variety of purposes such as creating assets, retrieving asset valuations etc.',
    license={
        'name': 'MIT',
        'url': 'https://github.com/XeroAPI/Xero-OpenAPI/blob/master/LICENSE',
    },
    termsOfService='https://developer.xero.com/xero-developer-platform-terms-conditions/',
    title='Xero Assets API',
    version='2.9.4',
    servers=[
        {
            'description': 'Xero API servers',
            'url': 'https://api.xero.com/assets.xro/1.0',
        }
    ],
)


@app.get(
    '/AssetTypes',
    description=""" By passing in the appropriate options, you can search for available fixed asset types in the system """,
    tags=['asset_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_asset_types(xero_tenant_id: str = Header(..., alias='xero-tenant-id')):
    """
    searches fixed asset types
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/AssetTypes',
    description=""" Adds an fixed asset type to the system """,
    tags=['asset_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def create_asset_type(
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'), body: AssetType = None
):
    """
    adds a fixed asset type
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Assets',
    description=""" By passing in the appropriate options, you can search for available fixed asset in the system """,
    tags=['asset_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_assets(
    status: AssetStatusQueryParam,
    page: Optional[int] = None,
    page_size: Optional[int] = Query(None, alias='pageSize'),
    order_by: Optional[OrderBy] = Query(None, alias='orderBy'),
    sort_direction: Optional[SortDirection] = Query(None, alias='sortDirection'),
    filter_by: Optional[str] = Query(None, alias='filterBy'),
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'),
):
    """
    searches fixed asset
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Assets',
    description=""" Adds an asset to the system """,
    tags=['asset_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def create_asset(
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'), body: Asset = ...
):
    """
    adds a fixed asset
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Assets/{id}',
    description=""" By passing in the appropriate asset id, you can search for
a specific fixed asset in the system
 """,
    tags=['asset_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_asset_by_id(
    id: UUID, xero_tenant_id: str = Header(..., alias='xero-tenant-id')
):
    """
    Retrieves fixed asset by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Settings',
    description=""" By passing in the appropriate options, you can search for available fixed asset types in the system """,
    tags=['asset_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_asset_settings(xero_tenant_id: str = Header(..., alias='xero-tenant-id')):
    """
    searches fixed asset settings
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
