# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:23:34+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, Field, RootModel


class AssetStatus(Enum):
    Draft = 'Draft'
    Registered = 'Registered'
    Disposed = 'Disposed'


class AssetStatusQueryParam(Enum):
    DRAFT = 'DRAFT'
    REGISTERED = 'REGISTERED'
    DISPOSED = 'DISPOSED'


class BookDepreciationDetail(BaseModel):
    costLimit: Optional[float] = Field(
        None,
        description='The value of the asset you want to depreciate, if this is less than the cost of the asset.',
        examples=[9000],
    )
    currentAccumDepreciationAmount: Optional[float] = Field(
        None,
        description='All depreciation occurring in the current financial year.',
        examples=[5],
    )
    currentCapitalGain: Optional[float] = Field(
        None,
        description='When an asset is disposed, this will be the sell price minus the purchase price if a profit was made.',
        examples=[5.25],
    )
    currentGainLoss: Optional[float] = Field(
        None,
        description='When an asset is disposed, this will be the lowest one of sell price or purchase price, minus the current book value.',
        examples=[10.5],
    )
    depreciationStartDate: Optional[date] = Field(
        None, description='YYYY-MM-DD', examples=['2015-07-01T00:00:00']
    )
    priorAccumDepreciationAmount: Optional[float] = Field(
        None,
        description='All depreciation prior to the current financial year.',
        examples=[0.45],
    )
    residualValue: Optional[float] = Field(
        None,
        description="The value of the asset remaining when you've fully depreciated it.",
        examples=[10000],
    )


class AveragingMethod(Enum):
    FullMonth = 'FullMonth'
    ActualDays = 'ActualDays'


class DepreciationCalculationMethod(Enum):
    Rate = 'Rate'
    Life = 'Life'
    None_ = 'None'


class DepreciationMethod(Enum):
    NoDepreciation = 'NoDepreciation'
    StraightLine = 'StraightLine'
    DiminishingValue100 = 'DiminishingValue100'
    DiminishingValue150 = 'DiminishingValue150'
    DiminishingValue200 = 'DiminishingValue200'
    FullDepreciation = 'FullDepreciation'


class BookDepreciationSetting(BaseModel):
    averagingMethod: Optional[AveragingMethod] = Field(
        None,
        description='The method of averaging applied to this asset. See Averaging Methods',
        examples=['ActualDays'],
    )
    bookEffectiveDateOfChangeId: Optional[UUID] = Field(
        None,
        description='Unique Xero identifier for the effective date change',
        examples=['68f17094-af97-4f1b-b36b-013b45b6ad3c'],
    )
    depreciableObjectId: Optional[UUID] = Field(
        None,
        description='Unique Xero identifier for the depreciable object',
        examples=['68f17094-af97-4f1b-b36b-013b45b6ad3c'],
    )
    depreciableObjectType: Optional[str] = Field(
        None, description='The type of asset object', examples=['Asset']
    )
    depreciationCalculationMethod: Optional[DepreciationCalculationMethod] = Field(
        None, description='See Depreciation Calculation Methods', examples=['None']
    )
    depreciationMethod: Optional[DepreciationMethod] = Field(
        None,
        description='The method of depreciation applied to this asset. See Depreciation Methods',
        examples=['StraightLine'],
    )
    depreciationRate: Optional[float] = Field(
        None, description='The rate of depreciation (e.g. 0.05)', examples=[0.05]
    )
    effectiveLifeYears: Optional[int] = Field(
        None, description='Effective life of the asset in years (e.g. 5)', examples=[5]
    )


class FieldValidationErrorsElement(BaseModel):
    detail: Optional[str] = Field(
        None, description='Detail of the field validation error'
    )
    fieldName: Optional[str] = Field(
        None, description='The field name of the erroneous field'
    )
    localisedMessage: Optional[str] = Field(
        None, description='Explanation of the field validation error'
    )
    title: Optional[str] = Field(
        None, description='Title of the field validation error'
    )
    type: Optional[str] = Field(
        None, description='Internal type of the field validation error message'
    )
    valueProvided: Optional[str] = Field(None, description='The provided value')


class Pagination(BaseModel):
    itemCount: Optional[int] = Field(None, examples=[2])
    page: Optional[int] = Field(None, examples=[1])
    pageCount: Optional[int] = Field(None, examples=[1])
    pageSize: Optional[int] = Field(None, examples=[10])


class ResourceValidationErrorsElement(BaseModel):
    detail: Optional[str] = Field(
        None, description='Detail of the resource validation error'
    )
    localisedMessage: Optional[str] = Field(
        None, description='Explanation of the resource validation error'
    )
    resourceName: Optional[str] = Field(
        None, description='The field name of the erroneous field'
    )
    title: Optional[str] = Field(
        None, description='Title of the resource validation error'
    )
    type: Optional[str] = Field(
        None, description='Internal type of the resource error message'
    )


class Setting(BaseModel):
    assetNumberPrefix: Optional[str] = Field(
        None,
        description='The prefix used for fixed asset numbers (“FA-” by default)',
        examples=['FA-'],
    )
    assetNumberSequence: Optional[str] = Field(
        None, description='The next available sequence number', examples=['0022']
    )
    assetStartDate: Optional[date] = Field(
        None,
        description='The date depreciation calculations started on registered fixed assets in Xero',
        examples=['2015-07-31T00:00:00'],
    )
    defaultCapitalGainOnDisposalAccountId: Optional[UUID] = Field(
        None,
        description='Default account that capital gains are posted to',
        examples=['6d6a0bdb-e118-45d8-a023-2ad617ec1cb7'],
    )
    defaultGainOnDisposalAccountId: Optional[UUID] = Field(
        None,
        description='Default account that gains are posted to',
        examples=['346ddb97-739a-4274-b43b-66aa3218d17c'],
    )
    defaultLossOnDisposalAccountId: Optional[UUID] = Field(
        None,
        description='Default account that losses are posted to',
        examples=['1b798541-24e2-4855-9309-c023a0b576f3'],
    )
    lastDepreciationDate: Optional[date] = Field(
        None, description='The last depreciation date', examples=['2015-07-01T00:00:00']
    )
    optInForTax: Optional[bool] = Field(
        None, description='opt in for tax calculation', examples=[False]
    )


class OrderBy(Enum):
    AssetType = 'AssetType'
    AssetName = 'AssetName'
    AssetNumber = 'AssetNumber'
    PurchaseDate = 'PurchaseDate'
    PurchasePrice = 'PurchasePrice'
    DisposalDate = 'DisposalDate'
    DisposalPrice = 'DisposalPrice'


class SortDirection(Enum):
    asc = 'asc'
    desc = 'desc'


class Asset(BaseModel):
    accountingBookValue: Optional[float] = Field(
        None, description='The accounting value of the asset', examples=[0]
    )
    assetId: Optional[UUID] = Field(
        None,
        description='The Xero-generated Id for the asset',
        examples=['3b5b3a38-5649-495f-87a1-14a4e5918634'],
    )
    assetName: str = Field(
        ..., description='The name of the asset', examples=['Awesome Truck 3']
    )
    assetNumber: Optional[str] = Field(
        None, description='Must be unique.', examples=['FA-0013']
    )
    assetStatus: Optional[AssetStatus] = None
    assetTypeId: Optional[UUID] = Field(
        None,
        description='The Xero-generated Id for the asset type',
        examples=['3b5b3a38-5649-495f-87a1-14a4e5918634'],
    )
    bookDepreciationDetail: Optional[BookDepreciationDetail] = None
    bookDepreciationSetting: Optional[BookDepreciationSetting] = None
    canRollback: Optional[bool] = Field(
        None,
        description="Boolean to indicate whether depreciation can be rolled back for this asset individually. This is true if it doesn't have 'legacy' journal entries and if there is no lock period that would prevent this asset from rolling back.",
        examples=[True],
    )
    disposalDate: Optional[date] = Field(
        None,
        description='The date the asset was disposed',
        examples=['2020-07-01T00:00:00'],
    )
    disposalPrice: Optional[float] = Field(
        None, description='The price the asset was disposed at', examples=['1.0000']
    )
    isDeleteEnabledForDate: Optional[bool] = Field(
        None,
        description='Boolean to indicate whether delete is enabled',
        examples=[True],
    )
    purchaseDate: Optional[date] = Field(
        None,
        description='The date the asset was purchased YYYY-MM-DD',
        examples=['2015-07-01T00:00:00'],
    )
    purchasePrice: Optional[float] = Field(
        None, description='The purchase price of the asset', examples=['1000.0000']
    )
    serialNumber: Optional[str] = Field(
        None,
        description="The asset's serial number",
        examples=['ca4c6b39-4f4f-43e8-98da-5e1f350a6694'],
    )
    warrantyExpiryDate: Optional[str] = Field(
        None,
        description='The date the asset’s warranty expires (if needed) YYYY-MM-DD',
        examples=['ca4c6b39-4f4f-43e8-98da-5e1f350a6694'],
    )


class AssetType(BaseModel):
    accumulatedDepreciationAccountId: Optional[UUID] = Field(
        None,
        description='The account for accumulated depreciation of fixed assets of this type',
        examples=['ca4c6b39-4f4f-43e8-98da-5e1f350a6694'],
    )
    assetTypeId: Optional[UUID] = Field(
        None,
        description='Xero generated unique identifier for asset types',
        examples=['5da209c5-5e19-4a43-b925-71b776c49ced'],
    )
    assetTypeName: str = Field(
        ..., description='The name of the asset type', examples=['Computer Equipment']
    )
    bookDepreciationSetting: BookDepreciationSetting
    depreciationExpenseAccountId: Optional[UUID] = Field(
        None,
        description='The expense account for the depreciation of fixed assets of this type',
        examples=['b23fc79b-d66b-44b0-a240-e138e086fcbc'],
    )
    fixedAssetAccountId: Optional[UUID] = Field(
        None,
        description='The asset account for fixed assets of this type',
        examples=['24e260f1-bfc4-4766-ad7f-8a8ce01de879'],
    )
    locks: Optional[int] = Field(
        None,
        description='All asset types that have accumulated depreciation for any assets that use them are deemed ‘locked’ and cannot be removed.',
        examples=[33],
    )


class Assets(BaseModel):
    items: Optional[List[Asset]] = None
    pagination: Optional[Pagination] = None


class Error(BaseModel):
    detail: Optional[str] = Field(None, description='Detail of the error')
    fieldValidationErrors: Optional[List[FieldValidationErrorsElement]] = Field(
        None, description='Array of elements of field validation errors'
    )
    resourceValidationErrors: Optional[List[ResourceValidationErrorsElement]] = Field(
        None, description='Array of elements of resource validation errors'
    )
    title: Optional[str] = Field(None, description='Title of the error')
    type: Optional[str] = Field(
        None, description='The internal type of error, not accessible externally'
    )


class AssetTypesGetResponse(RootModel[List[AssetType]]):
    root: List[AssetType]
